name: Docker Image CI

on:
  push:
    branches: [ master, feature/github_workflow ]
  pull_request:
    branches: [ master, feature/github_workflow ]

jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag offensiveanalytics:latest
    - name: Run image
      run: docker run offensiveanalytics:latest
    - name: Run tests
      run: docker exec -it offensiveanalytics:$ cd tests && sh runtests.sh
      
