name: Docker Image CI

on:
  push:
    branches: [ master, feature/github_workflow ]
  pull_request:
    branches: [ master, feature/github_workflow ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag offensiveanalytics:${{steps.vars.outputs.tag}}
      
  test:
    
    if: success()
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Run image
        run: docker run offensiveanalytics:${{steps.vars.outputs.tag}}
      - name: Run tests
        run: docker exec -it offensiveanalytics:${{steps.vars.outputs.tag}} sh tests/runtests.sh
