name: Docker Image CI

on:
  push:
    branches: [ master, feature/github_workflow ]
  pull_request:
    branches: [ master, feature/github_workflow ]

jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build . --file Dockerfile -t offensiveanalytics
    - name: Build tests
      run: docker build . --file Dockerfile.tests -t offensiveanalyticstests
    - name: Run tests
      run: docker run offensiveanalyticstests
    - name: Build release
      run: docker build . --file Dockerfile.app -t offensiveanalyticsapp
      
